# Generated by Django 4.1.4 on 2025-12-24 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nick', models.CharField(blank=True, max_length=25, null=True)),
                ('coins', models.IntegerField(default=200)),
                ('attributes', models.CharField(max_length=100)),
                ('prizes_earned', models.IntegerField(default=0)),
                ('last_rich_duel_game_number', models.IntegerField(default=-1)),
                ('last_aid_game_number', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('prob', models.FloatField()),
                ('value', models.FloatField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prizes_evolution',
            fields=[
                ('game_number', models.IntegerField(primary_key=True, serialize=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidor.player')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidor.prize')),
            ],
        ),
        migrations.CreateModel(
            name='Coins_evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField()),
                ('game_number', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidor.player')),
            ],
            options={
                'unique_together': {('player', 'game_number')},
            },
        ),
    ]
