# Generated by Django 4.1.4 on 2023-12-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nick',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
