# Generated by Django 4.1.4 on 2023-12-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0002_alter_player_nick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins_evolution',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prizes_evolution',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='coins_evolution',
            unique_together={('player', 'date', 'game_number')},
        ),
        migrations.AlterUniqueTogether(
            name='prizes_evolution',
            unique_together={('player', 'prize', 'date', 'game_number')},
        ),
    ]
