# Generated by Django 4.1.4 on 2024-12-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0004_remove_prizes_evolution_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='value',
            field=models.FloatField(),
        ),
    ]
