# Generated by Django 4.1.4 on 2024-12-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0005_alter_prize_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_duel',
            field=models.BooleanField(default=False),
        ),
    ]
