# Generated by Django 4.1.4 on 2024-12-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0007_remove_player_in_duel_player_rounds_since_last_duel'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='prizes_earned',
            field=models.IntegerField(default=0),
        ),
    ]
