# Generated by Django 4.1.4 on 2024-12-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0009_alter_coins_evolution_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='rounds_since_last_duel',
            new_name='last_duel_game_number',
        ),
    ]
