# Generated by Django 4.1.4 on 2024-12-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0010_rename_rounds_since_last_duel_player_last_duel_game_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_duel_game_number',
            field=models.IntegerField(default=-1),
        ),
    ]
