"""
Django settings for servidor_juegos project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import socket
import os
import platform
import subprocess

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-56@q90v8f-=ua&p)awa0bk9lepb8jte5)$8r0x6^+g)r76u17l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Determine local IP, preferring Wi‑Fi on Windows
def _get_wifi_ip_windows(timeout_seconds=2):
    """Try to get the IPv4 address of an active Wi‑Fi/WLAN adapter using PowerShell."""
    try:
        cmd = (
            "$adpt = Get-NetAdapter | Where-Object { $_.Status -eq 'Up' -and "
            "($_.Name -match 'Wi|Wireless|WLAN' -or $_.InterfaceDescription -match 'Wi|Wireless|WLAN') } | Select-Object -First 1; "
            "if ($adpt) { (Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex $adpt.ifIndex | "
            "Where-Object { $_.IPAddress -notmatch '^(169|127)' } | Select-Object -First 1 -ExpandProperty IPAddress) }"
        )
        proc = subprocess.run(["powershell", "-NoProfile", "-Command", cmd], capture_output=True, text=True, timeout=timeout_seconds)
        ip = proc.stdout.strip()
        if ip:
            return ip
    except Exception:
        pass
    return None


def _get_primary_ip():
    """Generic method: determine the IP used to reach the internet (no traffic sent)."""
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(('8.8.8.8', 80))
        ip = s.getsockname()[0]
    except Exception:
        ip = '127.0.0.1'
    finally:
        try:
            s.close()
        except Exception:
            pass
    return ip


def get_local_ip(prefer_wifi=True):
    ip = None
    if prefer_wifi and platform.system().lower().startswith('win'):
        ip = _get_wifi_ip_windows()
    if not ip:
        ip = _get_primary_ip()
    return ip

LOCAL_IP = get_local_ip(prefer_wifi=True)

# Allow hosts: prefer DJANGO_ALLOWED_HOSTS env var, otherwise use detected IP + loopback
env_allowed = os.environ.get('DJANGO_ALLOWED_HOSTS')
if env_allowed:
    ALLOWED_HOSTS = [h.strip() for h in env_allowed.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = [LOCAL_IP, '127.0.0.1', 'localhost']

# Application definition

INSTALLED_APPS = [
    'daphne', # Daphne ASGI server
    'channels', # Django Channels

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'servidor' # Servidor package
]

ASGI_APPLICATION = 'servidor_juegos.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

ROOT_URLCONF = 'servidor_juegos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'servidor_juegos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
